import { User, Chat, Message, StatusStory } from './types';

export const INITIAL_USERS: User[] = [
  {
    id: 'user-alex',
    name: 'Alex Rivera',
    username: 'alex_r',
    avatarColor: 'text-indigo-200',
    avatarBg: 'bg-gradient-to-br from-indigo-500 to-indigo-700',
    status: 'Building cool things with WhisperSync ⚡',
    isOnline: true,
    role: 'You (Product Lead)',
  },
  {
    id: 'user-liam',
    name: 'Liam Chen',
    username: 'liam_c',
    avatarColor: 'text-emerald-200',
    avatarBg: 'bg-gradient-to-br from-emerald-500 to-teal-700',
    status: 'In flow mode 🎧 Coding backend APIs',
    isOnline: true,
    lastSeen: 'Online',
    role: 'Lead Architect',
  },
  {
    id: 'user-maya',
    name: 'Maya Lin',
    username: 'maya_design',
    avatarColor: 'text-rose-200',
    avatarBg: 'bg-gradient-to-br from-rose-500 to-pink-700',
    status: 'Polishing mobile micro-interactions ✨',
    isOnline: true,
    lastSeen: '5m ago',
    role: 'Design Director',
  },
  {
    id: 'user-sophia',
    name: 'Sophia Patel',
    username: 'sophia_p',
    avatarColor: 'text-amber-200',
    avatarBg: 'bg-gradient-to-br from-amber-500 to-orange-700',
    status: 'Meeting clients · back at 3 PM',
    isOnline: false,
    lastSeen: '1h ago',
    role: 'VP Engineering',
  },
  {
    id: 'user-jordan',
    name: 'Jordan Blake',
    username: 'jordan_b',
    avatarColor: 'text-cyan-200',
    avatarBg: 'bg-gradient-to-br from-cyan-500 to-blue-700',
    status: 'Planning product release announcements 📣',
    isOnline: true,
    lastSeen: 'Online',
    role: 'Marketing Lead',
  },
];

export const INITIAL_MESSAGES: Record<string, Message[]> = {
  'chat-group-launch': [
    {
      id: 'msg-1',
      chatId: 'chat-group-launch',
      senderId: 'user-sophia',
      content: 'Morning team! Let’s lock in the milestone deliverables for v2.0 today.',
      timestamp: '09:15 AM',
      status: 'read',
      type: 'text',
      reactions: { '👍': ['user-alex', 'user-liam'], '🚀': ['user-maya'] },
    },
    {
      id: 'msg-2',
      chatId: 'chat-group-launch',
      senderId: 'user-maya',
      content: 'Working on the finalized design tokens! The new dark mode palettes look crisp.',
      timestamp: '09:18 AM',
      status: 'read',
      type: 'text',
      reactions: { '❤️': ['user-alex'] },
    },
    {
      id: 'msg-3',
      chatId: 'chat-group-launch',
      senderId: 'user-alex',
      content: 'Hey @Liam, quick question for later regarding server architecture.',
      timestamp: '09:22 AM',
      status: 'read',
      type: 'text',
      reactions: {},
    },
    {
      id: 'msg-4',
      chatId: 'chat-group-launch',
      senderId: 'user-alex',
      content: 'Hey Liam, keeping this off the group radar: Are we still preparing Maya’s surprise promotion gift basket for Friday? Don’t let her see this!',
      timestamp: '09:23 AM',
      status: 'read',
      type: 'whisper',
      reactions: { '🤫': ['user-liam'] },
      whisper: {
        isWhisper: true,
        targetUserIds: ['user-alex', 'user-liam'],
        targetNames: ['Alex Rivera', 'Liam Chen'],
        stealthLevel: 'stealth',
      },
    },
    {
      id: 'msg-5',
      chatId: 'chat-group-launch',
      senderId: 'user-liam',
      content: 'Yes! Got the customized artisan mechanical keyboard and coffee beans ordered. Stashed in my trunk 👍',
      timestamp: '09:24 AM',
      status: 'read',
      type: 'whisper',
      reactions: { '🎉': ['user-alex'] },
      replyTo: {
        id: 'msg-4',
        senderName: 'Alex Rivera',
        text: 'Hey Liam, keeping this off the group radar: Are we still preparing Maya’s surprise promotion...',
        isWhisper: true,
      },
      whisper: {
        isWhisper: true,
        targetUserIds: ['user-alex', 'user-liam'],
        targetNames: ['Alex Rivera', 'Liam Chen'],
        stealthLevel: 'stealth',
      },
    },
    {
      id: 'msg-6',
      chatId: 'chat-group-launch',
      senderId: 'user-maya',
      content: 'Here is a quick demo of how the new navigation tab transitions feel:',
      timestamp: '09:26 AM',
      status: 'read',
      type: 'text',
      reactions: { '🔥': ['user-liam', 'user-sophia'] },
    },
    {
      id: 'msg-7',
      chatId: 'chat-group-launch',
      senderId: 'user-liam',
      content: 'Here is a quick voice note explaining the WebSocket failover strategy:',
      timestamp: '09:30 AM',
      status: 'read',
      type: 'voice',
      voiceNote: {
        duration: 38,
        waveform: [20, 45, 60, 30, 80, 95, 65, 40, 75, 90, 50, 30, 70, 85, 40, 60, 75, 30, 55, 90, 45, 30],
      },
      reactions: { '👏': ['user-alex'] },
    },
    {
      id: 'msg-8',
      chatId: 'chat-group-launch',
      senderId: 'user-sophia',
      content: 'Quick poll for the release review meeting:',
      timestamp: '09:35 AM',
      status: 'read',
      type: 'poll',
      poll: {
        id: 'poll-1',
        question: 'What time suits best for the final team demo tomorrow?',
        options: [
          { id: 'opt-1', text: '10:00 AM PST', voterIds: ['user-sophia', 'user-maya'] },
          { id: 'opt-2', text: '02:00 PM PST', voterIds: ['user-alex', 'user-liam', 'user-jordan'] },
          { id: 'opt-3', text: '04:30 PM PST', voterIds: [] },
        ],
        isMultipleChoice: false,
        createdBy: 'user-sophia',
      },
      reactions: {},
    },
    {
      id: 'msg-9',
      chatId: 'chat-group-launch',
      senderId: 'user-alex',
      content: 'Public announcement: Everyone make sure to push staging PRs before 5 PM!',
      timestamp: '09:40 AM',
      status: 'read',
      type: 'text',
      reactions: { '👍': ['user-maya', 'user-liam', 'user-sophia'] },
    },
  ],
  'chat-group-weekend': [
    {
      id: 'wk-1',
      chatId: 'chat-group-weekend',
      senderId: 'user-jordan',
      content: 'Cabin booking confirmed! Lake Tahoe here we come 🌲🔥',
      timestamp: 'Yesterday',
      status: 'read',
      type: 'text',
      reactions: { '🥳': ['user-alex', 'user-maya'] },
    },
    {
      id: 'wk-2',
      chatId: 'chat-group-weekend',
      senderId: 'user-alex',
      content: 'Jordan, private whisper: What was the split deposit amount? Let me wire it directly.',
      timestamp: 'Yesterday',
      status: 'read',
      type: 'whisper',
      reactions: {},
      whisper: {
        isWhisper: true,
        targetUserIds: ['user-alex', 'user-jordan'],
        targetNames: ['Alex Rivera', 'Jordan Blake'],
        stealthLevel: 'stealth',
      },
    },
    {
      id: 'wk-3',
      chatId: 'chat-group-weekend',
      senderId: 'user-jordan',
      content: '$140 per head for the deposit. I’ll send you the Venmo QR.',
      timestamp: 'Yesterday',
      status: 'read',
      type: 'whisper',
      reactions: { '👍': ['user-alex'] },
      whisper: {
        isWhisper: true,
        targetUserIds: ['user-alex', 'user-jordan'],
        targetNames: ['Alex Rivera', 'Jordan Blake'],
        stealthLevel: 'stealth',
      },
    },
    {
      id: 'wk-4',
      chatId: 'chat-group-weekend',
      senderId: 'user-maya',
      content: 'Should we do a campfire taco night on Saturday?',
      timestamp: '10:02 AM',
      status: 'read',
      type: 'text',
      reactions: { '🌮': ['user-alex', 'user-liam', 'user-jordan'] },
    },
  ],
  'chat-direct-liam': [
    {
      id: 'dm-1',
      chatId: 'chat-direct-liam',
      senderId: 'user-liam',
      content: 'Hey Alex, do you have that benchmark latency report from AWS?',
      timestamp: '08:45 AM',
      status: 'read',
      type: 'text',
      reactions: {},
    },
    {
      id: 'dm-2',
      chatId: 'chat-direct-liam',
      senderId: 'user-alex',
      content: 'Yes! P99 latency dropped to 42ms after adding Redis caching in us-west.',
      timestamp: '08:50 AM',
      status: 'read',
      type: 'text',
      reactions: { '⚡': ['user-liam'] },
    },
  ],
  'chat-direct-maya': [
    {
      id: 'dmm-1',
      chatId: 'chat-direct-maya',
      senderId: 'user-maya',
      content: 'Hey Alex, check out the prototype when you get a chance! Let me know if the haptic feedback feels right.',
      timestamp: 'Yesterday',
      status: 'read',
      type: 'text',
      reactions: { '❤️': ['user-alex'] },
    },
  ],
};

export const INITIAL_CHATS: Chat[] = [
  {
    id: 'chat-group-launch',
    type: 'group',
    name: 'Launch Crew 🚀 · Product Alpha',
    avatarColor: 'text-violet-200',
    avatarBg: 'bg-gradient-to-tr from-violet-600 to-indigo-600',
    description: 'Core product engineering & design. Includes in-thread whisper testing.',
    members: [
      INITIAL_USERS[0], // Alex
      INITIAL_USERS[1], // Liam
      INITIAL_USERS[2], // Maya
      INITIAL_USERS[3], // Sophia
      INITIAL_USERS[4], // Jordan
    ],
    adminIds: ['user-sophia', 'user-alex'],
    unreadCount: 0,
    pinned: true,
    theme: 'whatsapp-emerald',
    disappearingTimer: 'off',
    whisperPrivacySetting: 'ghost',
    typingUsers: [],
    lastMessage: INITIAL_MESSAGES['chat-group-launch'][INITIAL_MESSAGES['chat-group-launch'].length - 1],
  },
  {
    id: 'chat-group-weekend',
    type: 'group',
    name: 'Lake Tahoe Trip 🌲🏕️',
    avatarColor: 'text-emerald-200',
    avatarBg: 'bg-gradient-to-tr from-emerald-600 to-cyan-700',
    description: 'Weekend cabin getaway coordination & secret expenses.',
    members: [
      INITIAL_USERS[0], // Alex
      INITIAL_USERS[1], // Liam
      INITIAL_USERS[2], // Maya
      INITIAL_USERS[4], // Jordan
    ],
    adminIds: ['user-jordan'],
    unreadCount: 1,
    pinned: true,
    theme: 'messenger-blue',
    disappearingTimer: 'off',
    whisperPrivacySetting: 'ghost',
    typingUsers: [],
    lastMessage: INITIAL_MESSAGES['chat-group-weekend'][INITIAL_MESSAGES['chat-group-weekend'].length - 1],
  },
  {
    id: 'chat-direct-liam',
    type: 'direct',
    name: 'Liam Chen',
    avatarColor: INITIAL_USERS[1].avatarColor,
    avatarBg: INITIAL_USERS[1].avatarBg,
    description: 'Senior Software Architect',
    members: [INITIAL_USERS[0], INITIAL_USERS[1]],
    adminIds: [],
    unreadCount: 0,
    pinned: false,
    theme: 'whatsapp-emerald',
    disappearingTimer: 'off',
    whisperPrivacySetting: 'ghost',
    typingUsers: [],
    lastMessage: INITIAL_MESSAGES['chat-direct-liam'][INITIAL_MESSAGES['chat-direct-liam'].length - 1],
  },
  {
    id: 'chat-direct-maya',
    type: 'direct',
    name: 'Maya Lin',
    avatarColor: INITIAL_USERS[2].avatarColor,
    avatarBg: INITIAL_USERS[2].avatarBg,
    description: 'Lead Product Designer',
    members: [INITIAL_USERS[0], INITIAL_USERS[2]],
    adminIds: [],
    unreadCount: 0,
    pinned: false,
    theme: 'sunset-rose',
    disappearingTimer: 'off',
    whisperPrivacySetting: 'ghost',
    typingUsers: [],
    lastMessage: INITIAL_MESSAGES['chat-direct-maya'][INITIAL_MESSAGES['chat-direct-maya'].length - 1],
  },
];

export const INITIAL_STATUS_STORIES: StatusStory[] = [
  {
    id: 'story-1',
    userId: 'user-maya',
    userName: 'Maya Lin',
    userAvatarBg: 'bg-gradient-to-br from-rose-500 to-pink-700',
    caption: 'Sunset sketch session 🎨 New palette ideas for the mobile experience!',
    timestamp: '25m ago',
    seen: false,
    mediaType: 'text',
    bgColor: 'from-fuchsia-600 to-rose-700',
  },
  {
    id: 'story-2',
    userId: 'user-liam',
    userName: 'Liam Chen',
    userAvatarBg: 'bg-gradient-to-br from-emerald-500 to-teal-700',
    caption: 'Brewing fresh single-origin espresso before the big code push ☕',
    timestamp: '2h ago',
    seen: false,
    mediaType: 'text',
    bgColor: 'from-emerald-700 to-teal-900',
  },
  {
    id: 'story-3',
    userId: 'user-jordan',
    userName: 'Jordan Blake',
    userAvatarBg: 'bg-gradient-to-br from-cyan-500 to-blue-700',
    caption: 'Tahoe trail hike prep! 🥾 Weather report says sunny all weekend.',
    timestamp: '4h ago',
    seen: true,
    mediaType: 'text',
    bgColor: 'from-blue-600 to-cyan-800',
  },
];
